### ISSUE TITLE
Sequence in bam output not the input sequence

### ISSUE THREAD

**Issue by karlol** [wanpinglee/MOSAIK#7]
The sequence in the bam file is not the same as was input to the alignment.

Steps to reproduce error:
1. wget ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/human_g1k_v37.fasta.gz
2. gunzip human_g1k_v37.fasta.gz
3. MosaikBuild -fr human_g1k_v37.fasta -ga v37 -oa human_g1k_v37.mosaik.dat -sn "Homo sapiens"
4. MosaikJump -ia human_g1k_v37.mosaik.dat -out human_g1k_v37.mosaik.15 -mem 24 -hs 15
5. cat > myseq.fa
   
   > myseq
   > CATGCTGCTAACGGTCGAGGTGCGA
   > ^D

6.
MosaikBuild -fr myseq.fa -out myseq.mos -st illumina -assignQual 306. MosaikBuild -fr myseq.fa -out myseq.mos -st ill\
umina -assignQual 30

7.
MosaikAligner -hs 15 -act 15 -min 20 -bw 11 -om -mm 4 -p 2 -ia human_g1k_v37.mosaik.dat -zn -j human_g1k_v37.mosaik.1\
5 -annse 2.1.78.se.ann -annpe 2.1.78.pe.ann -in myseq.mos -out aln1.out
samtools view aln1.out.bam
myseq   4       \*       0       0       \*       \*       0       0       CATGCTGCTAACGGTCGAGGTGCGA       ?????????????\
????????????     RG:Z:ZNZI48ZIRV6        ZN:Z:0;0;0;0;0;1

8.
MosaikAligner -hs 15 -act 15 -min 15 -bw 11 -om -mm 4 -p 2 -ia human_g1k_v37.mosaik.dat -zn -j human_g1k_v37.mosaik.1\
5 -annse 2.1.78.se.ann -annpe 2.1.78.pe.ann -in myseq.mos -out aln2.out
samtools view aln2.out.bam
myseq   16      6       95506098        29      15M10S  \*       0       0       ACCGTTAGCAGCATGTAGCAGCATG       ?????\
????????????????????     RG:Z:ZNZI48ZIRV6        NM:i:0  MD:Z:15 ZA:Z:<@;29;;;1;;>       ZN:Z:150;0;0;1.95352;1;1

The sequence in the bam-file from steps 7 and 8 should be the same as the input, which is only true for step 7.
The sequence in the bam-file from step 8 seems to be related to the input as follows:
The first 15 bases are the last 15 bases of the reverse complement of the input (ACCGTTAGCAGCATG).
The last 10 bases are the last 10 bases of the reverse complement of the input (TAGCAGCATG). So the part of the input sequence is duplicated and part is lost.

Below is an attempt to show this in aligned ascii:
Reverse complement input: TCGCACCTCGACCGTTAGCAGCATG
Output step 8:                      ACCGTTAGCAGCATGTAGCAGCATG
Output step 8:            ACCGTTAGCAGCATGTAGCAGCATG

MosaikAligner 2.2.19

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/R\
EADME.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --ena\
ble-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with\
-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-l\
ibstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32\
=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-\
linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by wanpinglee** [comment]
Dear Olof,

This is a terrible bug in MOSAIK and I appreciate that you point this out.
The bug is caused by using SSW information improperly. The problem has been
resolved. Please pull the up-to-date version for the fix.

Best,
Wan-Ping

On Mon, Mar 24, 2014 at 4:12 PM, Olof Karlberg notifications@github.comwrote:

> The sequence in the bam file is not the same as was input to the alignment.
> 
> Steps to reproduce error:
> 
>    1.
> 
>    wget
>    ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/human_g1k_v37.fasta.gz
>    2.
> 
>    gunzip human_g1k_v37.fasta.gz
>    3.
> 
>    MosaikBuild -fr human_g1k_v37.fasta -ga v37 -oa
>    human_g1k_v37.mosaik.dat -sn "Homo sapiens"
>    4.
> 
>    MosaikJump -ia human_g1k_v37.mosaik.dat -out human_g1k_v37.mosaik.15
>    -mem 24 -hs 15
>    5.
> 
>    cat > myseq.fa
> 
>    myseq
>    CATGCTGCTAACGGTCGAGGTGCGA
>    ^D
> 
> 6.
> MosaikBuild -fr myseq.fa -out myseq.mos -st illumina -assignQual 306.
> MosaikBuild -fr myseq.fa -out myseq.mos -st ill\
> umina -assignQual 30
> 
> 7.
> MosaikAligner -hs 15 -act 15 -min 20 -bw 11 -om -mm 4 -p 2 -ia
> human_g1k_v37.mosaik.dat -zn -j human_g1k_v37.mosaik.1\
> 5 -annse 2.1.78.se.ann -annpe 2.1.78.pe.ann -in myseq.mos -out aln1.out
> samtools view aln1.out.bam
> myseq 4 \* 0 0 \* \* 0 0 CATGCTGCTAACGGTCGAGGTGCGA ?????????????\
> ???????????? RG:Z:ZNZI48ZIRV6 ZN:Z:0;0;0;0;0;1
> 
> 8.
> MosaikAligner -hs 15 -act 15 -min 15 -bw 11 -om -mm 4 -p 2 -ia
> human_g1k_v37.mosaik.dat -zn -j human_g1k_v37.mosaik.1\
> 5 -annse 2.1.78.se.ann -annpe 2.1.78.pe.ann -in myseq.mos -out aln2.out
> samtools view aln2.out.bam
> myseq 16 6 95506098 29 15M10S \* 0 0 ACCGTTAGCAGCATGTAGCAGCATG ?????\
> ???????????????????? RG:Z:ZNZI48ZIRV6 NM:i:0 MD:Z:15 ZA:Z:<@;29;;;1;;>
> ZN:Z:150;0;0;1.95352;1;1
> 
> The sequence in the bam-file from steps 7 and 8 should be the same as the
> input, which is only true for step 7.
> The sequence in the bam-file from step 8 seems to be related to the input
> as follows:
> The first 15 bases are the last 15 bases of the reverse complement of the
> input (ACCGTTAGCAGCATG).
> The last 10 bases are the last 10 bases of the reverse complement of the
> input (TAGCAGCATG). So the part of the input sequence is duplicated and
> part is lost.
> 
> Below is an attempt to show this in aligned ascii:
> Reverse complement input: TCGCACCTCGACCGTTAGCAGCATG
> Output step 8: ACCGTTAGCAGCATGTAGCAGCATG
> Output step 8: ACCGTTAGCAGCATGTAGCAGCATG
> 
> MosaikAligner 2.2.19
> 
> gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5'
> --with-bugurl=file:///usr/share/doc/gcc-4.7/R\
> EADME.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr
> --program-suffix=-4.7 --enable-shared --ena\
> ble-linker-build-id --with-system-zlib --libexecdir=/usr/lib
> --without-included-gettext --enable-threads=posix --with\
> -gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls
> --with-sysroot=/ --enable-clocale=gnu --enable-l\
> ibstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object
> --enable-plugin --enable-objc-gc --with-arch-32\
> =i586 --with-tune=generic --enable-checking=release
> --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-\
> linux-gnu
> Thread model: posix
> gcc version 4.7.2 (Debian 4.7.2-5)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/wanpinglee/MOSAIK/issues/7
> .

## 

Wan-Ping Lee
Senior Research Associate
Department of Biology, Boston College

Tel: +1 (617) 552-2922
https://sites.google.com/site/wanpinglee

**Comment by karlol** [comment]
Dear Wan-Ping,

Thank you for the quick response, very much appreciated.

Regards,
Olof

26 mar 2014 kl. 19:36 skrev Wan-Ping:

> Dear Olof,
> 
> This is a terrible bug in MOSAIK and I appreciate that you point this out.
> The bug is caused by using SSW information improperly. The problem has been
> resolved. Please pull the up-to-date version for the fix.
> 
> Best,
> Wan-Ping
>
